### ISSUE TITLE
Easier way to get code snippets for example components

### ISSUE THREAD

**Issue by jalenmmorgan** [electrovir/vira#4] opened 2023-06-16 17:58 UTC
**Context**
The library is awesome. It shows a lot of different components and what they do. However there's not an easy way to see the actual code that created that component. You can't just look at the html because a lot of functionality is hidden there (host classes for example are applied via inputs, not `class="`. The easiest way I've found to get code snippets is to dig through the source code of the library and see what was done there. 

**Proposal** 
Either a button that lets me copy the string. Or display the code that generates that component somewhere. Even just showing what inputs were used for each code example would be very useful.

**Comment by electrovir** [comment] 2023-06-16 21:10
I think this is a duplicate of https://github.com/electrovir/element-book/issues/2

**Closed by electrovir** 2023-06-16 21:10 UTC
